// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: scraper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScrapingTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Selectors     map[string]string      `protobuf:"bytes,2,rep,name=selectors,proto3" json:"selectors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapingTask) Reset() {
	*x = ScrapingTask{}
	mi := &file_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapingTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapingTask) ProtoMessage() {}

func (x *ScrapingTask) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapingTask.ProtoReflect.Descriptor instead.
func (*ScrapingTask) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{0}
}

func (x *ScrapingTask) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ScrapingTask) GetSelectors() map[string]string {
	if x != nil {
		return x.Selectors
	}
	return nil
}

func (x *ScrapingTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScrapingTask) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ScrapingTask) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type ScrapingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Duration      int64                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	StatusCode    int32                  `protobuf:"varint,7,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	FromCache     bool                   `protobuf:"varint,8,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapingResult) Reset() {
	*x = ScrapingResult{}
	mi := &file_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapingResult) ProtoMessage() {}

func (x *ScrapingResult) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapingResult.ProtoReflect.Descriptor instead.
func (*ScrapingResult) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *ScrapingResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ScrapingResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ScrapingResult) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ScrapingResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ScrapingResult) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ScrapingResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ScrapingResult) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ScrapingResult) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

type AddTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*ScrapingTask        `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTasksRequest) Reset() {
	*x = AddTasksRequest{}
	mi := &file_scraper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTasksRequest) ProtoMessage() {}

func (x *AddTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTasksRequest.ProtoReflect.Descriptor instead.
func (*AddTasksRequest) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{2}
}

func (x *AddTasksRequest) GetTasks() []*ScrapingTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type AddTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTasksResponse) Reset() {
	*x = AddTasksResponse{}
	mi := &file_scraper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTasksResponse) ProtoMessage() {}

func (x *AddTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTasksResponse.ProtoReflect.Descriptor instead.
func (*AddTasksResponse) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{3}
}

func (x *AddTasksResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetResultsByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskIds       []string               `protobuf:"bytes,1,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultsByIdsRequest) Reset() {
	*x = GetResultsByIdsRequest{}
	mi := &file_scraper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultsByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultsByIdsRequest) ProtoMessage() {}

func (x *GetResultsByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultsByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetResultsByIdsRequest) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{4}
}

func (x *GetResultsByIdsRequest) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type GetResultsByIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ScrapingResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultsByIdsResponse) Reset() {
	*x = GetResultsByIdsResponse{}
	mi := &file_scraper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultsByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultsByIdsResponse) ProtoMessage() {}

func (x *GetResultsByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultsByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetResultsByIdsResponse) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{5}
}

func (x *GetResultsByIdsResponse) GetResults() []*ScrapingResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_scraper_proto protoreflect.FileDescriptor

const file_scraper_proto_rawDesc = "" +
	"\n" +
	"\rscraper.proto\x12\x05types\"\xc0\x02\n" +
	"\fScrapingTask\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12@\n" +
	"\tselectors\x18\x02 \x03(\v2\".types.ScrapingTask.SelectorsEntryR\tselectors\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12:\n" +
	"\aheaders\x18\x04 \x03(\v2 .types.ScrapingTask.HeadersEntryR\aheaders\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x1a<\n" +
	"\x0eSelectorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x02\n" +
	"\x0eScrapingResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x123\n" +
	"\x04data\x18\x03 \x03(\v2\x1f.types.ScrapingResult.DataEntryR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x03R\bduration\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1f\n" +
	"\vstatus_code\x18\a \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"from_cache\x18\b \x01(\bR\tfromCache\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x0fAddTasksRequest\x12)\n" +
	"\x05tasks\x18\x01 \x03(\v2\x13.types.ScrapingTaskR\x05tasks\"$\n" +
	"\x10AddTasksResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"3\n" +
	"\x16GetResultsByIdsRequest\x12\x19\n" +
	"\btask_ids\x18\x01 \x03(\tR\ataskIds\"J\n" +
	"\x17GetResultsByIdsResponse\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.types.ScrapingResultR\aresults2\x9f\x01\n" +
	"\x0eScraperService\x12;\n" +
	"\bAddTasks\x12\x16.types.AddTasksRequest\x1a\x17.types.AddTasksResponse\x12P\n" +
	"\x0fGetResultsByIds\x12\x1d.types.GetResultsByIdsRequest\x1a\x1e.types.GetResultsByIdsResponseB\x13Z\x11./pkg/types/protob\x06proto3"

var (
	file_scraper_proto_rawDescOnce sync.Once
	file_scraper_proto_rawDescData []byte
)

func file_scraper_proto_rawDescGZIP() []byte {
	file_scraper_proto_rawDescOnce.Do(func() {
		file_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scraper_proto_rawDesc), len(file_scraper_proto_rawDesc)))
	})
	return file_scraper_proto_rawDescData
}

var file_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_scraper_proto_goTypes = []any{
	(*ScrapingTask)(nil),            // 0: types.ScrapingTask
	(*ScrapingResult)(nil),          // 1: types.ScrapingResult
	(*AddTasksRequest)(nil),         // 2: types.AddTasksRequest
	(*AddTasksResponse)(nil),        // 3: types.AddTasksResponse
	(*GetResultsByIdsRequest)(nil),  // 4: types.GetResultsByIdsRequest
	(*GetResultsByIdsResponse)(nil), // 5: types.GetResultsByIdsResponse
	nil,                             // 6: types.ScrapingTask.SelectorsEntry
	nil,                             // 7: types.ScrapingTask.HeadersEntry
	nil,                             // 8: types.ScrapingResult.DataEntry
}
var file_scraper_proto_depIdxs = []int32{
	6, // 0: types.ScrapingTask.selectors:type_name -> types.ScrapingTask.SelectorsEntry
	7, // 1: types.ScrapingTask.headers:type_name -> types.ScrapingTask.HeadersEntry
	8, // 2: types.ScrapingResult.data:type_name -> types.ScrapingResult.DataEntry
	0, // 3: types.AddTasksRequest.tasks:type_name -> types.ScrapingTask
	1, // 4: types.GetResultsByIdsResponse.results:type_name -> types.ScrapingResult
	2, // 5: types.ScraperService.AddTasks:input_type -> types.AddTasksRequest
	4, // 6: types.ScraperService.GetResultsByIds:input_type -> types.GetResultsByIdsRequest
	3, // 7: types.ScraperService.AddTasks:output_type -> types.AddTasksResponse
	5, // 8: types.ScraperService.GetResultsByIds:output_type -> types.GetResultsByIdsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_scraper_proto_init() }
func file_scraper_proto_init() {
	if File_scraper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scraper_proto_rawDesc), len(file_scraper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scraper_proto_goTypes,
		DependencyIndexes: file_scraper_proto_depIdxs,
		MessageInfos:      file_scraper_proto_msgTypes,
	}.Build()
	File_scraper_proto = out.File
	file_scraper_proto_goTypes = nil
	file_scraper_proto_depIdxs = nil
}
